### ISSUE TITLE
Adapter does not connect - stays yellow

### ISSUE THREAD

**Issue by vansen** [afuerhoff/ioBroker.fb-checkpresence#158]
**Describe the bug**  
Adapter stays yellow. It says not connected to device or service. The user in Fritzbox is correctly setup and username and password are correct as well. TR-64 connector works fine.
Hopefully someone is able to help me.
Thanks

**To Reproduce**  
no repro steps, this error occurs since a few days.

**Expected behavior**  
Adapter should turn green. See log error below.

**Screenshots & Logfiles**  
This screenshot is from the log files section:
![image](https://user-images.githubusercontent.com/13270526/193888284-1da738da-8129-4f31-995f-6d36876ec76a.png)

**Versions:**  
 - Adapter version: 1.1.20
 - JS-Controller version: 4.0.23
 - Node version: 14.20
 - Operating system: ubuntu

**Additional context**  
None

**Comment by afuerhoff** [comment]
Hello, 
has the fritzbox user the correct access rights. Most of the services are deactivated. This is a sign for bad access rights or an incorrect password. Sometimes it helps to put in the password again because of the encryption function. 
Has you tried to reboot the fritzbox? 
Which Admin adapter version you have?

**Comment by afuerhoff** [comment]
No answer from creator of the issue
